// Code generated by bin/generate-interface-scaffold.mjs; DO NOT EDIT.
// Re-run the scaffold after changing config.yaml or pkg/idl public interfaces.
#pragma once

#include <cstdint>
#include <memory>
#include <vector>

#include "infra/communication/cpp/core/bootstrap.hpp"
#include "rclcpp/rclcpp.hpp"


#include "pkg/idl/middleware_rpc_client_test_service/generated/cpp/provider.hpp"
#include "pkg/idl/middleware_rpc_client_test_service/generated/cpp/registry.hpp"

// Module-local ROS2 typed callback shim generated from config.yaml and pkg/idl.
// Shared byte-level middleware route registration lives under pkg/idl.

namespace pacific_rim::generated::middleware_rpc_client_test {

struct GeneratedInterfaceHandles {

};

inline GeneratedInterfaceHandles register_generated_interfaces(
    rclcpp::Node& node,
    pacific_rim::communication::core::CommunicationRuntime& runtime) {
  GeneratedInterfaceHandles handles;
  (void)node;
  (void)runtime;
  pacific_rim::idl::MiddlewareRpcClientTestService::generated::Provider middleware_rpc_client_test_serviceProvider;

  pacific_rim::idl::MiddlewareRpcClientTestService::generated::RegisterGeneratedRpcRoutes(runtime, middleware_rpc_client_test_serviceProvider);

  return handles;
}

}  // namespace pacific_rim::generated::middleware_rpc_client_test
