"""Runtime communication adapters for Pacific-Rim modules."""

from .core import (
  Channel,
  CommunicationConfig,
  CommunicationFabric,
  CommunicationRuntime,
  CommunicationRuntimeThread,
  FanoutMessageBus,
  MessageBus,
  MiddlewareCapabilities,
  TypedMessageBus,
  bootstrap_communication,
  create_message_bus,
  create_message_bus_from_config,
  create_typed_message_bus,
  load_communication_config,
  load_communication_config_file,
  normalize_transport_kind,
)
from .contracts import (
  BridgeDirection,
  BridgeRule,
  CommunicationMessage,
  Endpoint,
  MessageEnvelope,
  MiddlewareConfig,
  PubSubRoute,
  RpcRoute,
  TransportKind,
)

__all__ = [
  "BridgeDirection",
  "BridgeRule",
  "Channel",
  "CommunicationConfig",
  "CommunicationFabric",
  "CommunicationMessage",
  "CommunicationRuntime",
  "CommunicationRuntimeThread",
  "Endpoint",
  "FanoutMessageBus",
  "MessageEnvelope",
  "MessageBus",
  "MiddlewareConfig",
  "MiddlewareCapabilities",
  "PubSubRoute",
  "RpcRoute",
  "TypedMessageBus",
  "TransportKind",
  "bootstrap_communication",
  "create_message_bus",
  "create_message_bus_from_config",
  "create_typed_message_bus",
  "load_communication_config",
  "load_communication_config_file",
  "normalize_transport_kind",
]
